### ISSUE TITLE
✨ Increasing score on pub.dev

### ISSUE THREAD

**Issue by mi-sch-ka** [michaeldonath/array-object-adapter#2]
To bring the pub score to the maximum, the source code must be formatted and an unnecessary null check must be removed.

See the [score on pub.dev](https://pub.dev/packages/array_object_adapter/score)

**Comment by Brainshaker95** [comment]
I would like to work on this issue

**Comment by mi-sch-ka** [comment]
@Brainshaker95 thanks for contributing 👍
